<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <EnableMSTestRunner>true</EnableMSTestRunner>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="bunit" Version="2.8.6" />
    <PackageReference Include="MSTest" Version="4.3.3" />
    <PackageReference Include="MudBlazor" Version="9.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\XFrame.Web\XFrame.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Bunit" />
    <Using Include="Microsoft.AspNetCore.Components.Authorization" />
    <Using Include="Microsoft.Extensions.DependencyInjection" />
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
    <Using Include="MudBlazor.Services" />
    <Using Include="XFrame.Web.Components.Pages.Editor" />
    <Using Include="XFrame.Web.Services.Abstract" />
    <Using Include="XFrame.Web.Services.Concrete" />
  </ItemGroup>

</Project>
